name: chatappocr
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retry: ^3.1.2 #for retrying Futures
  stacked: ^3.4.1 #for MVVM and State Management
  get_it: ^7.6.0 #for dependency injection
  injectable: ^2.3.0 #for dependency injection
  connectivity_plus: ^4.0.2 #for checking internet connection
  functional_widget_annotation: ^0.10.0 #for functional widgets
  intl: ^0.18.1 #for localization
  shared_preferences: ^2.2.0 #for storing data
  change_case: ^1.1.0 #for changing case of strings
  flutter_hooks: ^0.20.0 #for hooks using with functional_widget
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  injectable_generator: #for dependency injection
  build_runner: #for dependency injection
  flutter_lints: ^2.0.0 #for linting
  functional_widget: ^0.10.1 #for functional widgets


flutter:
  uses-material-design: true
  assets:
    - assets/strings/
